version: '3'
services:
  slackbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: slackbot:latest
    #user: slackbot
    container_name: slackbot_container_service
    networks:
      - net
    volumes:
      - ./assets:/assets
      - ./logs:/logs
      - ./lib:/lib
      - ./output:/output
      - ./.keys:/.keys
    environment:
      POSTGRES_PASSWORD_FILE: .keys/.pgdb_pass
      POSTGRES_DB: slackbot_prod
      POSTGRES_USER: slackbot
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
    #network_mode: host
  postgres:
    image: postgres:alpine
    networks:
      - net
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD_FILE: .keys/.pgdb_pass
      POSTGRES_DB: slackbot_prod
      POSTGRES_USER: slackbot
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
networks:
  net:
volumes:
  pg_data: