version: '3'
services:
  slackbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: slackbot:latest
    user: slackbot
    container_name: slackbot_container_service
    networks:
      - net
    links:
      - postgres
    environment:
      POSTGRES_PASSWORD_FILE: /home/slackbot/keys/.pgdb_pass
      POSTGRES_DB: slackbot_prod
      POSTGRES_USER: slackbot
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
    command: /bin/sh -c "pipenv install && pipenv run python slackbot.py prod"
    restart: unless-stopped
  postgres:
    image: postgres:alpine
    networks:
      - net
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pg_data
      - ./.keys:/keys
    environment:
      POSTGRES_PASSWORD_FILE: /keys/.pgdb_pass
      POSTGRES_DB: slackbot_prod
      POSTGRES_USER: slackbot
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
networks:
  net:
volumes:
  pg_data:
